---
title: "Predicting functional modules: gene families vs taxa"
author:
  - name: Giulio Benedetti
    affiliation: University of Turku
    email: giulio.benedetti@utu.fi
output:
    BiocStyle::html_document:
        fig_height: 7
        fig_width: 10
        toc: true
        toc_float: true
        toc_depth: 2
        number_sections: true
        self_contained: true
        code_folding: show
date: "`r doc_date()`"
package: "`r pkg_ver('ariadne')`"
vignette: >
    %\VignetteIndexEntry{Predicting functional modules: gene families vs taxa}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r lib, message=FALSE, warning=FALSE}
library(ariadne)
library(curatedMetagenomicData)
library(mia)
library(miaViz)
```

## Predicting modules from functional profile

```{r}
# Load gene family experiment
genes <- curatedMetagenomicData(
    "SankaranarayananK_2015.gene_families", dryrun = FALSE
)

genes <- genes[[1]]

# Keep only unstratified gene families
genes <- genes[!grepl("|", rownames(genes), fixed = TRUE), ]

# Print experiment
genes
```

```{r}
graph <- ariadne()

searchPath(graph, uniref90 ~ gmm, k = 3)
```

```{r}
# Weave bindings between taxa and GMMs
uniref2gmm <- weaveComplex(graph, uniref90 ~ gmm, k = 2, init = rownames(genes))

# Print some results
head(uniref2gmm)
```

```{r}
genes <- addModules(genes, uniref2gmm, as = "names")

uniref.modules <- agglomerateByModule(
    genes, by = "rows", group = unique(uniref2gmm$gmm.name)
)

uniref.modules
```

```{r}
top.mods <- getTop(uniref.modules, assay.type = "gene_families")

plotAbundance(
    modules[top.mods, ],
    assay.type = "gene_families",
    as.relative = TRUE
)
```

```{r}
plotAbundanceDensity(
    uniref.modules,
    assay.type = "gene_families",
    n = 5,
    layout = "density",
    colour.by = "disease"
)
```


## Predicting modules from taxonomic profile 

```{r}
tse <- curatedMetagenomicData(
    "SankaranarayananK_2015.relative_abundance",
    rownames = "NCBI",
    dryrun = FALSE
)

tse <- tse[[1]]

tse
```

```{r}
searchPath(graph, taxid ~ gmm, k = 3)
```

```{r}
# Link taxa to gut metabolic modules
tax2gmm <- weaveComplex(graph, taxid ~ gmm, k = 3, init = rowData(tse)$species)

head(tax2gmm)
```

```{r}
tse <- addModules(tse, tax2gmm, key = "species", as = "names")

tax.modules <- agglomerateByModule(
    tse, by = "rows", group = unique(tax2gmm$gmm.name)
)

tax.modules
```

```{r}
top.mods <- getTop(tax.modules, assay.type = "relative_abundance")

plotAbundance(
    tax.modules[top.mods, ],
    assay.type = "relative_abundance",
    as.relative = TRUE
)
```

```{r}
plotAbundanceDensity(
    tax.modules,
    assay.type = "relative_abundance",
    n = 5,
    layout = "density",
    colour.by = "disease"
)
```

## Correlating results

```{r}
mae <- MultiAssayExperiment(
    experiments = ExperimentList(uniref = uniref.modules, tax = tax.modules)
)
```

```{r}
cor <- getCrossAssociation(
    mae,
    assay.type1 = "gene_families",
    assay.type2 = "relative_abundance",
    sort = TRUE
)

cor$Var1 <- as.character(cor$Var1)
cor$Var2 <- as.character(cor$Var2)

cor <- cor[cor$Var1 == cor$Var2, ]
```

```{r}
ggplot(cor, aes(x = cor, y = reorder(Var1, cor))) +
    geom_point() +
    labs(y = "GMM") +
    theme_bw()
```

# Reproducibility

R session information:

```{r reproduce, echo=FALSE}
# Session info
options(width = 120)
sessionInfo()
```