---
title: "Microbe-Set Enrichment Analysis"
author:
  - name: Giulio Benedetti
    affiliation: University of Turku
    email: giulio.benedetti@utu.fi
output:
    BiocStyle::html_document:
        fig_height: 7
        fig_width: 10
        toc: true
        toc_float: true
        toc_depth: 2
        number_sections: true
        self_contained: true
        code_folding: show
date: "`r doc_date()`"
package: "`r pkg_ver('ariadne')`"
vignette: >
    %\VignetteIndexEntry{Microbe-Set Enrichment Analysis}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Incorporate relational knowledge in a dataset

```{r lib, message=FALSE, warning=FALSE}
library(ariadne)
library(mia)
library(miaViz)
```


```{r}
# Import dataset
data("Tengeler2020", package = "mia")
tse <- Tengeler2020

tse <- agglomerateByRank(tse, rank = "Genus")
tse <- transformAssay(tse, method = "relabundance")

tse
```

### Single-module analysis

```{r}
data("butyrate", package = "ariadne")

butyrate
```

```{r}
tse <- addModules(tse, butyrate, key = "Genus", as = "names")

modules <- agglomerateByModule(tse, by = "rows", group = "butyrate")

modules
```


```{r}
plotAbundance(modules)
```

```{r}
plotBoxplot(modules, assay.type = "relabundance", group.by = "patient_status")
```

### Multi-module analysis

```{r}
graph <- ariadne()

searchPath(graph, taxname ~ bugsig)
```

```{r}
tax2bugsig <- weavePath(graph, taxname ~ bugsig, init = rowData(tse)$Genus)

head(tax2bugsig)
```

```{r}
mod.names <- levels(tax2bugsig$bugsig.name)

adhd.mods <- mod.names[grepl("ADHD", mod.names)]

adhd.mods
```


```{r}
tse <- addModules(tse, tax2bugsig, key = "Genus", as = "names")

modules <- agglomerateByModule(tse, by = "rows", group = adhd.mods)

modules
```

```{r}
plotAbundance(modules)
```

```{r}
plotAbundanceDensity(
    modules,
    assay.type = "relabundance",
    layout = "density",
    colour.by = "patient_status"
)
```

```{r}
idx <- apply(rowData(tse)[adhd.mods], 2L, function(x) which(x))

to_keep <- lengths(idx) != 0L
idx <- idx[to_keep]
adhd.mods <- adhd.mods[to_keep]

res <- lapply(
    seq_along(adhd.mods),
    function(i) plotAbundance(tse[idx[[i]], ]) + ggtitle(adhd.mods[i])
)
```


```{r}
library(patchwork)
wrap_plots(res)
```

