name: update
on:
  schedule:
    # Runs at 00:00 UTC every Wednesday
    - cron: '0 0 * * 3'
jobs:
  cronjob:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install ariadne
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::systemfonts
            any::usethis
      - name: Run scripts
        run: |
          Rscript inst/scripts/make-versionMetadata.R
          Rscript inst/scripts/make-hexSticker.R
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add R/sysdata.rda inst/assets/ariadne_logo.png
          git commit -m 'Regenerate hex sticker'
          git push origin devel
